### ISSUE TITLE
Separate quickstarter config from application.properties

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#363]
**Is your feature request related to a problem? Please describe.**
At the moment, the `ConfigMap application.properties` defines which quickstarters are available: https://github.com/opendevstack/ods-provisioning-app/blob/master/ocp-config/prov-app/cm.yml. This is not ideal as it does not allow to compare the content of the file easily via Tailor when users change which quickstarters they want to use (e.g. if they point to internal quickstarters).

**Describe the solution you'd like**
It would be good to have the quickstarter configuration separately. This could be another ConfigMap, or a file. A ConfigMap has the advantage to be easily modifiable in the OCP UI.

**Comment by stitakis** [comment]
@michaelsauter  I first solution that comes to my mind is to move the current jenkinspipeline/quickstarters definition to a file (defined in oc as configmap) and modify the ProvApp to load this configuration from a default location/file. The file format could be json for easy convertion to the current `Quickstarter` java class/model.
Would this address the requirements, especially related to Tailor?

**Comment by michaelsauter** [comment]
Some questions:
* Where would this file be stored?
* How could we ship with a default set?

Since the file should be edited by humans, I suggest YAML instead of JSON.

One alternative I have thought about (though not sure yet if this is a good idea): One could have a ConfigMap, which is mounted as a file. Tailor has a flag called `--preserve`, which allows to preserve paths of live configuration when applying. One could use that to create the ConfigMap initially with some default quickstarters, but subsequent calls of `tailor apply` would not show drift in the ConfigMap.

**Comment by michaelsauter** [comment]
Here's my proposal for this, which I believe is the least effort to get it done for v3:

Add a `ConfigMap` like this:
```
apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: ods-provisioning-app
    name: quickstarters
  data:
    properties: |
      be-java-springboot:
        desc: Java SpringBoot
        repo: ods-quickstarters
      be-golang-plain:
        desc: Go
        repo: ods-quickstarters
```

Then, mount this file in the prov app, and read the YML. The structure of the YML is just an example, we might also use a top-level key ... not sure there.

Further, we ensure that this `ConfigMap` does not detect drift on its data. That allows to seed with defaults, but when users adapt the config, no drift is shown.

To achieve this with Tailor, we add the following line to the `Tailorfile`:
```
preserve cm: quickstarters:/data
```

@stitakis @oalyman Thoughts?
