### ISSUE TITLE
Ship provision app ocp artifacts w/o project in openshift directory

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#423]
**Is your feature request related to a problem? Please describe.**
In order to provision the prov App mit a Dev environment it should only contain the application specific ocp artifacts that de Provision with tailor. `metadata/name`, `namespace`  and `metadata/labels` have to be params.. so no diff is generated for contribution back upstream

Example(s):
```
  metadata:
    labels:
      app: prov-app
    name: prov-app
```

```
      to:
        kind: ImageStreamTag
        name: prov-app:${ODS_IMAGE_TAG}
```
