### ISSUE TITLE
Release manager failure for components starting with 'dev' due to tailor content replacing 

### ISSUE THREAD

**Issue by borja44** [opendevstack/ods-provisioning-app#521]
### **Describe the bug**

When we use the Release Manager to deploy the exported Openshift configuration file template.yml is wrong due to the name of the application we would like to deploy.

### **Wrong example "current behaviour":****
```
apiVersion: template.openshift.io/v1

 kind: Template

 objects:

 - apiVersion: v1

 kind: Service

 metadata:

 labels:

 app: ${TAILOR_NAMESPACE}ice-monitoring-fe-angular

 template: component-template

 name: device-monitoring-fe-angular
```

Check line starting with: 
app:

### Expected behavior Example:**

```
apiVersion: template.openshift.io/v1

 kind: Template

 objects:

 - apiVersion: v1

 kind: Service

 metadata:

 labels:

 app: ${TAILOR_NAMESPACE}-device-monitoring-fe-angular

 template: component-template

 name: device-monitoring-fe-angular
```
Check line starting with: 
app:

**Affected version

OpenDevstack 2.x
We've tested this on an Angular quickstarter, may it happens with the rest of boilerplates.

**Additional context**
We've detected too in the same file, when the line app: ${TAILOR_NAMESPACE} repeats again, the error happens again.

**Additional context2**
The name of the application we are using starts with dev, and we think the issue is here. (Jenkins shared library or tailor is probably the root cause of the issue).
